#include "TIW.h"

void TIW(
        const char* inst_name, // Instance name
        bool Rst,
        width_t *CIW,
        width_t *CFW,
        int_part_t *IV,
        fp_data_t *y1, // Golden output
        fp_data_t *y2, // DUT output
        fp_data_t x
        ){
#pragma HLS INLINE off
#pragma HLS FUNCTION_INSTANTIATE variable=inst_name

    // ============================================================
    // **Explanation**
    // The maximum integer and fractional widths are used by the
    // Golden instance. These widths define the reference precision
    // against which the configurable DUT is evaluated.
    //
    // IVNum must correspond to the number of intermediate variables
    // defined by the application.
    // ============================================================

    width_t MIW[IVNum];
    width_t MFW[IVNum];

	// ============================================================
	// **Explanation**
	// Storage for intermediate values generated by the DUT.
	// ============================================================
	//
	// Intermediate values are required from the Golden instance for
	// dynamic-range analysis. The corresponding DUT array is retained
	// to keep the application interface consistent between the two
	// instances.
	
    int_part_t sIVDUT[IVNum];

    fp_data_t sy1, sy2;

    // ============================================================
    // **Explanation**
    // Application state/memory elements are instantiated here rather
    // than inside the framework itself.
    //
    // Replace the following placeholders with the state elements
    // required by the application. For example, a recursive filter
    // may require delay/state registers, while a stateless
    // application may not require any persistent state.
    //
    // Separate state elements are required for the Golden and DUT
    // instances.
    // ============================================================

    // static fp_data_t application_state_G[...];
    // static fp_data_t application_state_D[...];

    // ============================================================
    // **Explanation**
    // Provide the application input to both instances.
    //
    // The same input sample is evaluated by the Golden and DUT
    // instances so that their outputs can be compared.
    // ============================================================

    fp_data_t sx1 = x;
    fp_data_t sx2 = x;

    // ============================================================
    // **Explanation**
    // Golden application instance.
    //
    // Set GoldenInst = true. The application must use the reference
    // / maximum widths for this instance.
    //
    // The application-specific state/memory elements for the Golden
    // instance are passed here if required.
    // ============================================================

    Application(
        Golden_Instance_Name,
        true,
        Rst,
        CIW,
        CFW,
        sx1,
        &sy1
        /* application-specific state/memory ports */
    );

    // ============================================================
    // **Explanation**
    // DUT application instance.
    //
    // Set GoldenInst = false. The application must use the runtime
    // integer and fractional widths supplied through CIW and CFW.
    //
    // The application-specific state/memory elements for the DUT
    // instance are passed here if required.
    // ============================================================

    Application(
        DUT_Instance_Name,
        false,
        Rst,
        CIW,
        CFW,
        sx2,
        &sy2
        /* application-specific state/memory ports */
    );

    *y1 = sy1;
    *y2 = sy2;
}